config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root_path
  root "homes#top"
  get "help" => "homes#help"
  get "guidline" => "homes#guid"
  get "convention" => "homes#conv"
  get "privacypolicy" => "homes#priv"
  get "contact" => "homes#contact"


  resources :homes, only: [:top, :help, :guid, :conv, :priv, :contact]

  resources :posts do
  	resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show] do
  	member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :news
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true, length: { maximum: 155 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  counter_culture :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/new.rb
class New < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  is_impressionable
  mount_uploader :image, ImageUploader
  validates :title, presence: true, length: { maximum: 25 }
  validates :description, presence: true, length: { maximum: 255 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :username, presence: true, length: { maximum: 50 }
  validates :profile, length: { maximum: 500 }
  has_many :posts, dependent: :destroy
  has_many :news, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  mount_uploader :avatar, AvatarUploader


  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
   
  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :username, :profile, :avatar, :email, :password, :password_confirmation　]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
  	@post = Post.find(params[:post_id])
  	@comments = @post.comments 
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      # flash.now[:alert] = '投稿できませんでした。内容を確認してください。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @news = New.all.order(id: "DESC")
    @posts = Post.all.order(id: "DESC")
  end

  def help
  end

  def guid
  end

  def conv
  end

  def priv
  end

  def contact
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_new, only: [:show, :edit, :update, :destroy]

  def index
  	@news = New.all.order(id: "DESC")
  end

  def show
  end

  def new
  	@new = New.new
  end

  def create
  	@new = New.new(new_params)
    @new.user_id = current_user.id
  	if @new.save
  	  redirect_to news_path(@new)
  	else
  	  render 'new'
  	end
  end

  def edit
  end

  def update
  	if @new.update(new_params)
      redirect_to @new
    else
      render 'new'
    end
  end

  def destroy
    @new.destroy
    redirect_to news_index_path
  end

  def ensure_correct_user
    @new = New.find_by(id:params[:id])
    if @new.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to root_path
    end
  end

  private

    def new_params
      params.require(:new).permit(:head, :article)
    end

    def set_new
      @new = New.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  impressionist :actions=> [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
  	@q = Post.ransack(params[:q])
    @posts = @q.result
    @posts = @q.result.page(params[:page]).per(10)
  end

  def show
    impressionist(@post, nil, unique: [:session_hash])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
  	@post = Post.new
  end

  def create 
  	@post = Post.new(post_params)
    @post.user_id = current_user.id
  	if @post.save
      flash[:notice] = '投稿が完了しました。'
  	  redirect_to @post
  	else
      flash.now[:alert] = '投稿できませんでした。内容を確認してください。'
  	  render :new
  	end
  end

  def edit 
  end

  def update
  	if @post.update(post_params)
      flash[:notice] = '投稿を編集しました。'
  	  redirect_to @post
  	else
      flash.now[:alert] = '編集できませんでした。内容を確認してください。'
  	  render 'edit'
  	end
  end

  def destroy
  	@post.destroy
    flash[:notice] = '投稿を削除しました。'
  	redirect_to root_path
  end

  private

    def set_post
  	  @post = Post.find(params[:id])
    end

    def post_params
  	  params.require(:post).permit(:title, :description, :image)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end


  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  require "uri"

	def text_url_to_link text

	  URI.extract(text, ['http', 'https']).uniq.each do |url|
	    sub_text = ""
	    sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

	    text.gsub!(url, sub_text)
	  end

	  return text
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/likes/_like.html.slim
- if user_signed_in?
  - unless post.like_user(current_user.id).blank?
    = link_to post_like_path(post_id: post.id, id: post.likes[0].id), method: :delete, remote: true do
      .vertical_like

        span style='red'
          = post.likes_count
  - else
    = link_to post_likes_path(post.id), method: :post, remote: true do
      .vertical_like

        span
          = post.likes_count
- else
  - if post.likes_count > 0
    .vertical_like
      span style='red'
        = post.likes_count
  - else
    .vertical_like
      span
        = post.likes_count

app/views/likes/create.js.erb
| $("#likes_buttons_#{@post.id}").html("#{j(render partial: 'likes/like', locals: { post: @post })}");

app/views/news/edit.html.slim
h1 アップデート情報編集

= form_for(@new, url: { action: "update" }) do |f|

  .field
    = f.label :head
    = f.text_field :head, class: 'form-control'

  .field
    = f.label :article
    = f.text_area :article, class: 'form-control'

  .action
    = f.submit "投稿", class: 'btn btn-primary'

= link_to 'Back', news_index_path

app/views/news/index.html.slim
h1 アップデート情報

- @news.each do |new|
  h3 = link_to new.head, news_path(new)
  p = new.article.truncate(140, omission: '...')
  p = new.updated_at.strftime("%-Y年%-m月%-d日")


= link_to "new", new_news_path

app/views/news/new.html.slim
h1 アップデート情報書き込み

= form_for(@new, url: { action: "create" }) do |f|

  .field
    = f.label :head
    = f.text_field :head, class: 'form-control'

  .field
    = f.label :article
    = f.text_area :article, class: 'form-control'

  .action
    = f.submit "投稿", class: 'btn btn-primary'



= link_to 'Back', news_index_path

app/views/news/show.html.slim
h1 = @new.head

p = simple_format text_url_to_link(h(@new.article)).html_safe

p = "更新日：#{@new.updated_at.strftime("%-Y年%-m月%-d日")}"


= link_to "destroy", @new, method: :delete, data: { confirm: 'destroy?' } 

br

= link_to "edit", edit_news_path

br

= link_to 'Back', news_index_path

app/views/posts/_form.html.slim
= form_with(model: post, local: true) do |f|

  .field
    = f.label :title
    = f.text_field :title, class: 'form-control'

  .field
    = f.label :description
    = f.text_area :description, class: 'form-control'

  .field
    = f.label :image
    = f.file_field :image, class: 'form-control'

  .action
    = f.submit "投稿", class: 'btn btn-primary'

app/views/posts/edit.html.slim
= render 'form', post: @post

app/views/posts/index.html.slim
.search-form
  = search_form_for @q do |f| 
    = f.label :title, "タイトル"
    = f.search_field :title_cont, class: "search-field", :placeholder => "検索"
    = button_tag type: 'submit', class: "btn btn-primary" do
      i.fas.fa-search
    li = sort_link(@q, :created_at, '投稿日時', default_order: :desc)

h1 新着投稿

- @posts.each do |post|
  ul
    li = link_to image_tag(post.image_url.to_s, controls: true, width: 550, height: 400, id: "image", alt: "image"), post
    li = link_to post.title, post

= paginate @posts

app/views/posts/new.html.slim
= render 'form', post: @post

= link_to 'Back', root_path

app/views/posts/show.html.slim
= image_tag @post.image.url

h2 = @post.title

p = simple_format text_url_to_link(h(@post.description)).html_safe

i.fas.fa-eye
  = @post.impressionist_count

i.far.fa-thumbs-up id= "likes_buttons_#{@post.id}"
  = render partial: 'likes/like', locals: { post: @post, likes: @likes }

p 投稿日時: #{@post.updated_at.strftime("%Y年%-m月%-d日 %-H時%-M分")}

- if user_signed_in? && @post.user.id == current_user.id
  i.far.fa-edit
  = link_to 'edit', edit_post_path
  span |
  = link_to 'destroy', @post, method: :delete, data: { confirm: '削除してもよろしいですか？' }


p = link_to @post.user.username, user_path(@post.user)


= form_for [@post, @comment] do |f|
  = f.text_field :content, :placeholder => "コメントする..."
  = button_tag type: 'submit', data: { confirm: "コメントを投稿しますか？"}, class: 'btn btn-primary' do
    i.far.fa-paper-plane

br

- @comments.each do |comment|
  = link_to "#{comment.user.username}", "/users/#{comment.user_id}"
  p = comment.content
  - if user_signed_in? && comment.user_id == current_user.id
    = link_to "削除", [@post, comment], method: :delete, data: { confirm: '削除?' }
  p = "作成日時:#{time_ago_in_words(comment.created_at)}前"
  hr